config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord

  validates :title, presence: true, length: { minimum:6, maximum:100 }
  validates :description, presence: true, length: { minimum:10, maximum:300 }

end  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
 
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show
    
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
    
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = 'Article was created successfully'
      redirect_to article_path(@article)
    else
      render 'new', status: :unprocessable_entity
    end

  end

  def update
    
    if @article.update(article_params)
      flash[:notice] = 'Article was updated successfully'
      redirect_to article_path(@article)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end  

  def article_params
    params.require(:article).permit(:title, :description)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  
  end 

  def about

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/articles/_form.html.erb
<div class="container">

  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors' %>
      <%= form_with(model: @article, class:"shadow p-3 mb-3 bg-info rounded", local: true ) do |f| %>
        <div class="form-group row mb-2">
          <%= f.label :title, class:"col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title,  class:"form-control shadow-sm bg-body rounded", placeholder: "Title of article" %> 
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :description, class:"col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_area :description, rows:10, class:"form-control shadow-sm bg-body rounded", placeholder: "Description of article" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <div class="col-2">
            <%= f.submit class:"btn btn-outline-light btn-lg mt-3" %>
          </div>
        </div>

      <% end %>
    </div>

      <%= link_to '[Cancel and return to articles index]', articles_path,class:"text-center", method: :get %>

  </div>
</div>

app/views/articles/edit.html.erb
<div id="page-content">
  <h1 class="text-center mt-4 text-white">Edit Article</h1>

  <%= render 'form' %>
  
</div>

app/views/articles/index.html.erb
<h1 class='text-center mt-4 text-white'>Showing Articles Index</h1>

<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center ">
      <div class="col-6 mt-4 shadow mb-5 px-0 bg-body rounded">
        <div class="card text-center">
          <div class="card-header fst-italic">
              By Boris Pulido
            </div>
            <div class="card-body">
              <h5 class="card-title"><%= link_to article.title, article_path(article), class:"text-success" %></h5>
              <p class="card-text"><%= article.description %></p>
              <div class="container">
                <%= link_to 'View', article_path(article.id),class:"btn btn-outline-success", method: :get %>
                <%= link_to 'Edit', edit_article_path(article.id),class:"btn btn-outline-info", method: :get %>
                <%= link_to 'Delete', article_path(article.id),class:"btn btn-outline-danger", form: { data: { turbo_confirm: 'Are you sure?' }}, method: :delete %>
              </div>
            </div>
            <div class="card-footer text-muted">
              <small>Created <%= time_ago_in_words(article.created_at) %> ago, edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<div id="page-content">
  <h1 class="text-center mt-4 text-white">Create new article</h1>

  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div id="page-content">
<h2 class='text-center mt-4 text-white'><%= @article.title %></h2>

<div class="container">
  
    <div class="row justify-content-md-center ">
      <div class="col-6 mt-4 shadow mb-5 px-0 bg-body rounded">
        <div class="card text-center">
          <div class="card-header fst-italic">
              By Boris Pulido
            </div>
            <div class="card-body">
              <div class="card-text"><%= simple_format(@article.description) %></div>
              <div class="container">
                <%= link_to 'Edit', edit_article_path(@article.id),class:"btn btn-outline-info", method: :get %>
                <%= link_to 'Delete', article_path(@article.id),class:"btn btn-outline-danger", form: { data: { turbo_confirm: 'Are you sure?' }}, method: :delete %>
              </div>
            </div>
            <div class="card-footer text-muted">
              <small>Created <%= time_ago_in_words(@article.created_at) %> ago, edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright 2022</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
    <div class="container">
    <% flash.each do |name,msg| %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= msg %>
         <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    </div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">

    <%= link_to 'RAILS APP', root_path, class: "navbar-brand", id: "logo", data: { "turbo-method": :get }%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to 'Index', articles_path, class: "nav-link active", data: { "turbo-method": :get } %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Create new article", new_article_path, class: "dropdown-item"%></li>
            <li><%= link_to "View articles", articles_path, class: "dropdown-item"%></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link active", data: { "turbo-method": :get }  %>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1 class="text-center text-white">About</h1>

<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo cum quasi dignissimos reiciendis dolorem ab facere minima aut recusandae illo, est porro, quaerat asperiores expedita soluta sequi excepturi. Ea totam sit architecto fuga perferendis, eligendi rem officia magni neque ipsam sapiente? Incidunt officia labore autem eum molestias quia, odio iusto at ducimus culpa repudiandae eligendi ad laudantium tempore, earum blanditiis voluptatem voluptate magnam velit quod! Nisi facere, libero ex quisquam praesentium deleniti sint exercitationem fugit fuga odit delectus laborum non fugiat aliquid quaerat eveniet dolores earum sunt sit. Tempora, reprehenderit quisquam! Commodi dicta explicabo dolorum harum natus? Hic ad voluptate accusamus. Nisi aperiam ut quisquam error nemo earum autem maiores est repellat quibusdam. Molestias nam dolore voluptas inventore quos atque neque, minus dignissimos, praesentium sit nobis. Omnis quibusdam illo sapiente eveniet. Veritatis hic consectetur eligendi libero! Voluptate, sed. Voluptate optio, voluptas voluptatum quibusdam expedita vero aliquam asperiores fuga! Voluptatibus, perferendis?</p>

app/views/pages/home.html.erb
<div class="container">

  <h1 id="title"><span>RAILS</span><span>APP</span></h1>

</div>

app/views/shared/_errors.html.erb
<% if @article.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the article from being saved:</h4>
    <hr>   
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
    </ul>
     <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>    


<% end %>